# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: make-nasdaq-directory
        run: mkdir $GITHUB_WORKSPACE/nasdaq
      # Runs a single command using the runners shell
      - name: get-nasdaq
        #https://www.nasdaq.com/market-activity/stocks/screener?exchange=nyse&letter=0&render=download
        run: "curl --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:85.0) Gecko/20100101 Firefox/85.0' https://api.nasdaq.com/api/screener/stocks\\?tableonly\\=true\\&limit\\=25\\&offset\\=0\\&exchange\\=nasdaq\\&download\\=true >> /tmp/nasdaq.json"
      - name: gen-stock-tickers-json
        run: "cat /tmp/nasdaq.json | jq '.data.rows' >> $GITHUB_WORKSPACE/nasdaq/nasdaq_full_tickers.json"
      - name: gen-stock-tickers-json
        run: "cat /tmp/nasdaq.json | jq '[.data.rows | .[] | .symbol]' >> $GITHUB_WORKSPACE/nasdaq/nasdaq_tickers.json"
      - name: gen-stock-tickers-txt
        run: "cat /tmp/nasdaq.json | jq '[.data.rows | .[] | .symbol]' | grep -Ei '([A-Za-z]+)' -o >> $GITHUB_WORKSPACE/nasdaq/nasdaq_tickers.txt"
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
      
      
